# Generated by Django 5.2.7 on 2025-11-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MGNREGAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_year', models.CharField(blank=True, max_length=20, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district_code', models.CharField(blank=True, max_length=10, null=True)),
                ('district_name', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_labour_budget', models.FloatField(blank=True, null=True)),
                ('average_wage_rate', models.FloatField(blank=True, null=True)),
                ('total_expenditure', models.FloatField(blank=True, null=True)),
                ('total_households_worked', models.IntegerField(blank=True, null=True)),
                ('women_persondays', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
